build_script:
  - cmd: dotnet format
  - cmd: dotnet build -c Release
  - cmd: dotnet build -c Debug
  # - cmd: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - cmd: doxygen Doxyfilef
  - cmd: cd docs
  - cmd: git add --all
  - cmd: git commit -m "Update documentation"
  - cmd: git push -u origin main
