build_script:
  - cmd: dotnet format
  - cmd: dotnet build -c Release
  - cmd: dotnet build -c Debug
  # - cmd: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - cmd: doxygen Doxyfile
  - cmd: git config --global credential.helper store
  - cmd: git config --global user.email "zluo3@wpi.edu"
  - cmd: git config --global user.name "garyluozhuang"
  - cmd: cd docs
  - cmd: git add --all
  - cmd: git commit -m "Update documentation"
  - cmd: git push origin main
